version: "3.8"

services:
  db:
    container_name: "workoutDB"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_Db: "postgress"
      POSTGRES_User: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
